kenzo: camera: include missing header file
 hardware/qcom/media-caf/msm8952/libstagefrighthw/QComOMXMetadata.h:21:10:
 fatal error: 'system/window.h' file not found

Signed-off-by: dodyirawan85 <dev.irawans@gmail.com>